
name: 'Testing'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4 
      with:
        python-version: 'pypy3.9' 
    - run: echo "<pre><code>$(python my_script.py)</code></pre>" >> $GITHUB_STEP_SUMMARY