name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production
    
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      id: plan
      run: |
        terraform plan -no-color

    - name: Plan File
      run: echo  " ${{ steps.plan.outputs.stdout }} " >> TerraformPlanFiles/terraformplan

    - name: Echo Plan File
      run: cat TerraformPlanFiles/terraformplan

    - name: Conditoining 
      run: |
        FILESIZE=$(stat -c%s "TerraformPlanFiles/test.txt")
        MAXSIZE=1000000
        echo "Size of $FILENAME = $FILESIZE bytes."
        if (( FILESIZE < MAXSIZE)); then 
            echo "<pre><code>${{ steps.plan.outputs.stdout }}</code></pre>" >> $GITHUB_STEP_SUMMARY
        else
          cd TerraformPlanFiles
          split -b $MAXSIZE test.txt tfplan
          ls
          for entry in "tfplan"*
          do
            echo "$entry"
          done
        fi

